# config.yaml
# path to the bam files
bam_dir: "test"

# path to results
output_dir: "test_output"

# path to reference genome
reference_genome: "/tmp/global2/hxu/hxu_snake/genome/dmel-all-chromosome-r6.14.fasta"

# path to SNP database
dbSNP: "dbSNP_Nex_Sep28.19.vcf"

# path to bed file
bed_file: "test.bed"
